// Code generated by "stringer -type=BufferCondition"; DO NOT EDIT.

package internal

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[IsEmpty-0]
	_ = x[IsRunning-1]
}

const _BufferCondition_name = "IsEmptyIsRunning"

var _BufferCondition_index = [...]uint8{0, 7, 16}

func (i BufferCondition) String() string {
	if i < 0 || i >= BufferCondition(len(_BufferCondition_index)-1) {
		return "BufferCondition(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BufferCondition_name[_BufferCondition_index[i]:_BufferCondition_index[i+1]]
}
